name: encoding-warnings
version: 0.05
abstract: Warn on implicit encoding conversions
author: Autrijus Tang <autrijus@autrijus.org>
license: perl
distribution_type: module
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.35
