abstract: Warn on implicit encoding conversions
author: Audrey Tang
distribution_type: module
generated_by: Module::Install version 0.63
license: perl
name: encoding-warnings
no_index: 
  directory: 
    - inc
    - t
requires: 
  perl: 5.7.0
version: 0.10
